services:
  task-trackerDB:
    image: mongo:5.0.0
    container_name: task_tracker-database
    restart: always
    ports:
      - "27017:21017"
    environment:
        MONGO_DB: ${MONGO_URI}
    volumes:
      - ./mongo:/data/db